# Generated by Django 5.2.1 on 2025-06-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='api.college'),
        ),
    ]
